### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by mariohahn** [vtourraine/VTAcknowledgementsViewController#47]

**Comment by vtourraine** [comment]
It didn't cross my mind, but yes, I’m all for it. 

I know that `UITableViewController` is also available for tvOS, so I wonder how much change it would require to make the existing classes compatible (the result on screen would look very different, of course). Have you tried it?

On a similar note, it would be fun to offer a watchOS controller too. This one would have to be clearly distinct, because WatchKit isn’t built on top of UIKit. I’ll probably create a dedicated GitHub Issue, in case someone wants to send a Pull Request later on.
