### ISSUE TITLE
URL can not be seen

### ISSUE THREAD

**Issue by hiseri** [vtourraine/VTAcknowledgementsViewController#52]
Color of URL in TextView is same color with tintColor
So, if tintColor is white, URL can not be seen.

Check this issue, please.
Thank you.

**Comment by vtourraine** [comment]
Thanks for bringing this up.

I’m not sure that, in this situation, the acknowledgements controller should update its `tintColor` by itself. Because if the app does have a custom color scheme, then the controller doesn’t know what the expected links color is.

Can you try to set the acknowledgements controller view `tintColor` property before pushing it onscreen, or use the `UIAppearance` API to customize the different tint colors for your app (nav bar, text view, etc)?

**Comment by hiseri** [comment]
Thank you for answering!

I could solve this issue using UIAppearance API in AppDelegate.
```Objective-C
[UITextView appearance].linkTextAttributes = @{NSForegroundColorAttributeName: [UIColor blueColor], NSUnderlineStyleAttributeName: [NSNumber numberWithInt:NSUnderlineStyleSingle]};
```

Thank you very much! 😄
