### ISSUE TITLE
Setting backgroundColor of table view removes the Done button

### ISSUE THREAD

**Issue by honkmaster** [vtourraine/VTAcknowledgementsViewController#53]
Hi @vtourraine.

Thanks for this great component. I want to use your component and change the backgroundcolor of the table view. Therefore I init the VTAcknowledgementsViewController as follows:

``` objc
VTAcknowledgementsViewController *acknowledgementsViewController = [[VTAcknowledgementsViewController alloc] initWithFileNamed:@"Foo"];
acknowledgementsViewController.view.backgroundColor = [UIColor greencolor];

// Present acknowledgementsViewController
UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:acknowledgementsViewController];
[self.navigationController presentViewController:navigationController animated:YES completion:nil];
```

The backgroundColor of the table view  is now green. However, now the Done button is missing. If I remove setting of the backgroundColor everything is back to normal <=> Done button is visible. 

Where is my mistake? Any Idea? If you need help, e.g. a demo project, do not hesitate contacting me.

BR

Tobias

**Comment by honkmaster** [comment]
FYI: It is happening on iOS 10, Simulator as well as on device.

**Comment by honkmaster** [comment]
Investigated: Seams like line the if statement in line 215 in `VTAcknowledgementsViewController.m` (if (self.presentingViewController && self == [self.navigationController.viewControllers firstObject])) resolves to false if a backgroundcolor is set as shown above and thus a UIBarButtonItem is never created and set.

**Comment by vtourraine** [comment]
Hello Tobias! Really sorry about this late reply.

So the problem is that when you set a custom background color, you access the `view` property before it's been loaded by the usual presentation flow. Therefore, the view controller loads it, then performs `viewDidLoad`, where the Done button is configured. And because at this point your view controller hasn't been added to its modal navigation controller, it's treated as being part of a basic navigation controller stack, relying on the system Back button.

So, the real problem is that we should test the modal vs. navigation stack situation from another method, to make sure that we configure the Done button if – and only if – necessary. The usual solution is to test this in `viewWillAppear`, I think. That doesn't feel completely right either, because for instance popping a specific acknowledgement controller will then re-test it. Maybe I'm over-thinking it, I just want to avoid other issues by calling it too late instead.

What do you think?

**Comment by honkmaster** [comment]
Hi, no problem. In such a case I would normally prefer a property, such as .backgroundColor, which you can later on use whenever you want. Thus, the workflow would be as follows.

```
VTAcknowledgementsViewController *acknowledgementsViewController = [[VTAcknowledgementsViewController alloc] initWithFileNamed:@"Foo"];
acknowledgementsViewController.backgroundColor = [UIColor greencolor];
```

**Comment by vtourraine** [comment]
I agree that the customisation should be straightforward, just like in your code snippet, but I don't think that adding a new property would be a sustainable solution. Because then every piece of customisable interface would need its own property, despite the fact that these properties already exist.

I really think we should fix the Done button configuration instead. I'll try to do that very soon, unless you want to go ahead and send a pull request.

**Comment by vtourraine** [comment]
I've added a new branch [`done-button`](https://github.com/vtourraine/VTAcknowledgementsViewController/tree/done-button), where I moved the modal presentation test to `viewWillAppear`, as previously discussed.

Could you please test this branch, and see if it fixes this issue?

**Comment by honkmaster** [comment]
Will do this evening. Thanks.
